moviesstore/cart/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='cart.index'),
    path('<int:id>/add/', views.add, name='cart.add'),
    path('clear/', views.clear, name='cart.clear'),
    path('purchase/', views.purchase, name='cart.purchase'),
]

moviesstore/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='movies.index'),
    path('<int:id>/', views.show, name='show'),
    path('<int:id>/review/create/', views.create_review, name='create_review'),
    path('<int:id>/review/<int:review_id>/edit/', views.edit_review, name='edit_review'),
    path('<int:id>/review/<int:review_id>/delete/', views.delete_review, name='delete_review'),
]

moviesstore/moviesstore/urls.py
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('movies/', include('movies.urls', namespace='movies')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

moviesstore/movies/models.py
from django.db import models
from django.contrib.auth.models import User

class Movie(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.TextField()
    image = models.ImageField(upload_to='movie_images/')
    def __str__(self):
        return str(self.id) + ' - ' + self.name

class Review(models.Model):
    id = models.AutoField(primary_key=True)
    comment = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)
    movie = models.ForeignKey(Movie,
        on_delete=models.CASCADE)
    user = models.ForeignKey(User,
        on_delete=models.CASCADE)
    def __str__(self):
        return str(self.id) + ' - ' + self.movie.name

moviesstore/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie, Review
from django.contrib.auth.decorators import login_required

@login_required
def edit_review(request, id, review_id):
    review = get_object_or_404(Review, id=review_id)
    if request.user != review.user:
        return redirect('movies.show', id=id)
    if request.method == 'GET':
        template_data = {}
        template_data['title'] = 'Edit Review'
        template_data['review'] = review
        return render(request, 'movies/edit_review.html',
            {'template_data': template_data})
    elif request.method == 'POST' and request.POST['comment'] != '':
        review = Review.objects.get(id=review_id)
        review.comment = request.POST['comment']
        review.save()
        return redirect('movies:show', id=id)
    else:
        return redirect('movies:show', id=id)
def index(request):
    search_term = request.GET.get('search')
    if search_term:
        movies = Movie.objects.filter(name__icontains=search_term)
    else:
        movies = Movie.objects.all()
    template_data = {}
    template_data['title'] = 'Movies'
    template_data['movies'] = movies
    print(template_data)
    return render(request, 'movies/index.html',
                  {'template_data': template_data})

def show(request, id):
    movie = Movie.objects.get(id=id)
    reviews = Review.objects.filter(movie=movie)
    template_data = {}
    template_data['title'] = movie.name
    template_data['movie'] = movie
    template_data['reviews'] = reviews
    return render(request, 'movies/show.html',
                  {'template_data': template_data})

@login_required
def create_review(request, id):
    if request.method == 'POST' and request.POST['comment'] != '':
        movie = Movie.objects.get(id=id)
        review = Review()
        review.comment = request.POST['comment']
        review.movie = movie
        review.user = request.user
        review.save()
        return redirect('movies:show', id=id)
    else:
        return redirect('movies:show', id=id)

@login_required
def delete_review(request, id, review_id):
    review = get_object_or_404(Review, id=review_id,
        user=request.user)
    review.delete()
    return redirect('movies:show', id=id)

moviesstore/movies/templates/movies/edit_review.html
{% extends 'base.html' %}
{% block content %}
<div class="p-3">
  <div class="container">
    <div class="row mt-3">
      <div class="col mx-auto mb-3">
        <h2>Edit Review</h2>
        <hr />
        <form method="POST">
          {% csrf_token %}
          <p>
            <label for="comment">Comment:</label>
            <textarea name="comment" required
            class="form-control" id="comment">{{template_data.review.comment }}</textarea>
          </p>
          <div class="text-start">
            <button type="submit"
              class="btn bg-dark text-white">Edit Review
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

moviesstore/movies/templates/movies/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="p-3">
  <div class="container">
    <div class="row mt-3">
      <div class="col mx-auto mb-3">
        <h2>List of Movies</h2>
        <hr />
        <p class="card-text">
          <form method="GET">
            <div class="row">
              <div class="col-auto">
                <div class="input-group col-auto">
                  <div class="input-group-text">
                    Search</div>
                  <input type="text" class="form-control"
                    name="search">
                </div>
              </div>
              <div class="col-auto">
                <button class="btn bg-dark text-white"
                  type="submit">Search</button>
              </div>
            </div>
          </form>
        </p>
      </div>
    </div>
    <div class="row">
      {% for movie in template_data.movies %}
      <div class="col-md-4 col-lg-3 mb-2">
        <div class="p-2 card align-items-center pt-4">
          <img src="{{ movie.image.url }}"
            class="card-img-top rounded img-card-200">
          <div class="card-body text-center">
            <a href="{% url 'movies:show' id=movie.id %}" class="btn bg-dark text-white">
            {{ movie.name }}
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock content %}

moviesstore/movies/templates/movies/show.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="p-3">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-6 mx-auto mb-3">
        <h2>{{ template_data.movie.name }}</h2>
        <hr />
        <p><b>Description:</b> {{template_data.movie.description}}</p>
        <p><b>Price:</b> ${{template_data.movie.price}}</p>
      <p class="card-text">
          <form method="post"
            action="{% url 'cart.add' id=template_data.movie.id %}">
            <div class="row">
              {% csrf_token %}
              <div class="col-auto">
                <div class="input-group col-auto">
                  <div class="input-group-text">Quantity
                    </div>
                  <input type="number" min="1" max="10"
                    class="form-control quantity-input"
                    name="quantity" value="1">
                </div>
              </div>
              <div class="col-auto">
                <button class="btn bg-dark text-white"
                  type="submit">Add to cart</button>
              </div>
            </div>
          </form>
        </p>
      <h2>Reviews</h2>
        <hr />
        <ul class="list-group">
          {% for review in template_data.reviews %}
          <li class="list-group-item pb-3 pt-3">
            <h5 class="card-title">
              Review by {{ review.user.username }}
            </h5>
            <h6 class="card-subtitle mb-2 text-muted">
              {{ review.date }}
            </h6>
            <p class="card-text">{{ review.comment }}</p>
          {% if user.is_authenticated and user == review.user %}
            <a class="btn btn-primary"
              href="{% url 'movies:edit_review' template_data.movie.id review.id %}">Edit
            </a>
              <a class="btn btn-danger"
              href="{% url 'movies:delete_review' template_data.movie.id review.id %}">Delete
            </a>
            {% endif %}
          </li>
          {% endfor %}
        </ul>
          {% if user.is_authenticated %}
        <div class="container mt-4">
          <div class="row justify-content-center">
            <div class="col-12">
              <div class="card shadow p-3 mb-4 rounded">
                <div class="card-body">
                  <b class="text-start">Create a review
                    </b><br /><br />
                  <form method="POST" action=
                    "{% url 'movies:create_review' template_data.movie.id %}">
                    {% csrf_token %}
                    <p>
                      <label for="comment">Comment:</label>
                      <textarea name="comment" required
                      class="form-control"
                      id="comment"></textarea>
                    </p>
                    <div class="text-center">
                      <button type="submit"
                        class="btn bg-dark text-white">
                        Add Review
                      </button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
      </div>
      <div class="col-md-6 mx-auto mb-3 text-center">
        <img src="{{ template_data.movie.image.url }}"
      class="rounded img-card-400" />
      </div>
    </div>
  </div>
</div>
{% endblock content %}